name: Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build Linux binary
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build emissary-cli
        run: cargo build --release --no-default-features --features web-ui

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/emissary-cli
          draft: true
          prerelease: false
