name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
        toolchain: nightly

    - name: cargo-fmt emissary-core
      working-directory: emissary-core
      run: cargo +nightly fmt -- --check

    - name: cargo-fmt emissary-cli
      working-directory: emissary-cli
      run: cargo +nightly fmt -- --check

    - name: cargo-fmt emissary-util
      working-directory: emissary-util
      run: cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy

    - name: cargo-clippy emissary-core
      working-directory: emissary-core
      run: cargo clippy -- -D warnings

    - name: cargo-clippy emissary-cli
      working-directory: emissary-cli
      run: cargo clippy -- -D warnings

    - name: cargo-clippy emissary-util
      working-directory: emissary-util
      run: cargo clippy --all-features -- -D warnings

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: cargo-check emissary-core no-std
      working-directory: emissary-core
      run: cargo check --no-default-features --features no_std

    - name: cargo-check emissary-cli web-ui
      working-directory: emissary-cli
      run: cargo check --no-default-features --features web-ui
